more configure foo testing

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3458,6 +3458,8 @@ FOLLOW_READLINK ()
   echo $myprog
 }
 
+ERR_MSG=""
+FOUND_ERROR=
 
 
 
@@ -4383,8 +4385,9 @@ if test ${with_lua+y}
 then :
   withval=$with_lua; PATH_TO_LUA="$withval"
     if test ${PATH_TO_LUA:0:1} != '/' ; then
-      echo "Path to lua must be absolute"
-      FOUND_ERROR=yes
+      echo
+      echo "ERROR: Path to lua must be absolute!"
+      exit 1
     fi
     { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: PATH_TO_LUA=$with_lua" >&5
 printf "%s\n" "PATH_TO_LUA=$with_lua" >&6; }
@@ -4406,8 +4409,9 @@ if test ${with_luac+y}
 then :
   withval=$with_luac; PATH_TO_LUAC="$withval"
     if test ${PATH_TO_LUAC:0:1} != '/' ; then
-      echo "Path to luac must be absolute"
-      FOUND_ERROR=yes
+      echo
+      echo "ERROR: Path to luac must be absolute"
+      exit 1
     fi
     { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: PATH_TO_LUAC=$with_luac" >&5
 printf "%s\n" "PATH_TO_LUAC=$with_luac" >&6; }
@@ -4447,8 +4451,6 @@ if test "$ALLOW_TCL_MFILES" = no ; then
   FAST_TCL_INTERP=no
 fi
 
-FOUND_ERROR=
-
 if test "$FAST_TCL_INTERP" = yes ; then
    OS=$(uname -s)
    if test "$OS" = Darwin ; then
@@ -4456,7 +4458,7 @@ if test "$FAST_TCL_INTERP" = yes ; then
      TCL_INCLUDE="-I${DIR}/usr/include"
    else
      for i in "" tcl tcl8.8 tcl8.7 tcl8.6 tcl8.5; do
-        if test -f /usr/include/$i/tcl.h ; then
+        if test -f /usr/include/$i/tcl.hh ; then
 	   TCL_INCLUDE="-I/usr/include/$i"
 	   break;
 	fi
@@ -4464,8 +4466,8 @@ if test "$FAST_TCL_INTERP" = yes ; then
    fi
 
    if test -z "$TCL_INCLUDE" ; then
-       # Extract the first word of "pkg-config", so it can be a program name with args.
-set dummy pkg-config; ac_word=$2
+       # Extract the first word of "pkg-configFoo", so it can be a program name with args.
+set dummy pkg-configFoo; ac_word=$2
 { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
 printf %s "checking for $ac_word... " >&6; }
 if test ${ac_cv_path_pkgConfig+y}
@@ -4554,8 +4556,8 @@ then :
 printf "%s\n" "#define STDC_HEADERS 1" >>confdefs.h
 
 fi
-ac_fn_c_check_header_compile "$LINENO" "tcl.h" "ac_cv_header_tcl_h" "$ac_includes_default"
-if test "x$ac_cv_header_tcl_h" = xyes
+ac_fn_c_check_header_compile "$LINENO" "tcl.hh" "ac_cv_header_tcl_hh" "$ac_includes_default"
+if test "x$ac_cv_header_tcl_hh" = xyes
 then :
 
 printf "%s\n" "#define HAVE_TCL_H 1" >>confdefs.h
@@ -4566,8 +4568,10 @@ fi
    if test "$ac_cv_header_tcl_h" != yes ; then
       rm -f makefile
       FOUND_ERROR=yes
-      { printf "%s\n" "$as_me:${as_lineno-$LINENO}: Unable to build Lmod without tcl.h.  Please install the tcl devel package or configure --with-fastTCLInterp=no to not require tcl.h" >&5
-printf "%s\n" "$as_me: Unable to build Lmod without tcl.h.  Please install the tcl devel package or configure --with-fastTCLInterp=no to not require tcl.h" >&6;}
+      MSG="Unable to build Lmod without tcl.h.  Please install the tcl devel package or configure --with-fastTCLInterp=no to not require tcl.h"
+      ERR_MSG="$ERR_MSG||$MSG"
+      { printf "%s\n" "$as_me:${as_lineno-$LINENO}: $MSG" >&5
+printf "%s\n" "$as_me: $MSG" >&6;}
    fi
    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for library containing Tcl_CreateInterp" >&5
 printf %s "checking for library containing Tcl_CreateInterp... " >&6; }
@@ -4661,14 +4665,25 @@ PATH_TO_SRC=$SRCDIR
 
 
 
-if test $MODE != "user_default" ; then
-  mode=0$MODE
+FOUND_ERROR=yes
+MSG="MODE must have at least one executable bit set (Not MODE=$MODE)|
+Please try setting mode to 755 or 750 or 700 or similar."
+
+     echo "$MSG"
+     echo
+ERR_MSG="$ERR_MSG||$MSG"
+
+if test $MODE == "user_default" ; then
+  mode=0755
   EXEC_BITS=$(( 0111 & $mode ));
   if test $EXEC_BITS = 0; then
+MSG="MODE must have at least one executable bit set (Not MODE=$MODE)
+Please try setting mode to 755 or 750 or 700 or similar."
+
+     echo "$MSG"
      echo
-     echo "MODE must have at least one executable bit set (Not MODE=$MODE)"
-     echo "Please try setting mode to 755 or 750 or 700 or similar."
-     echo
+ERR_MSG="$ERR_MSG
+$MSG"
      rm -f makefile
      FOUND_ERROR=yes
   fi
@@ -5673,8 +5688,15 @@ fi
 
 if test $FOUND_ERROR = yes; then
   echo
-  echo One or more errors found -> Quiting!
+  echo One or more errors found:
   echo
+  echo Error Messages:
+  echo "------------------------------------------------------------"
+  echo $ERR_MSG | tr '|' '\n' | while read item; do
+       echo $item
+  done
+  echo "------------------------------------------------------------"
+
   rm -f makefile
   exit 1;
 fi
