Testing Lmod_test_suite

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -47,9 +47,16 @@ jobs:
          git clone https://github.com/rtmclay/Lmod_test_suite.git
          cd -
          cd /tmp/Lmod_test_suite
-         pwd
-         ls
          tm -k normal
-         cd -
+      - name: show output of failed tests
+        if: ${{ failure() }}
+        run: |
+         # diff stdout/stderr for all tests in case of failure
+         for dir in $(ls -pd rt/* | grep '/$'); do
+           echo ">>>> ${dir}/err.txt"
+           diff -c ${dir}t1/*/_err.left ${dir}/t1/*/_err.right || echo
+           echo ">>>> ${dir}/out.txt"
+           diff -c ${dir}/out.txt ${dir}/t1/*/out.txt || echo
+         done
          
         
